##############################################################################
# MODULE: COMPUTE
# Resources:
#   - Availability Set for the Web VMs
#   - 2x Linux VMs in the Web subnet (inside the Availability Set)
#   - 1x Linux VM in the Management subnet
#
# OS Image (all three VMs):
#   Publisher : Canonical
#   Offer     : 0001-com-ubuntu-server-jammy
#   SKU       : 22_04-lts-gen2   (Ubuntu Server 22.04 LTS - Gen2)
#   Version   : latest
#
# SSH keys are generated by tls_private_key resources in the root module
# and passed in via ssh_public_key_web / ssh_public_key_mgmt variables.
# The corresponding private keys are stored in Key Vault by the security module.
##############################################################################

locals {
  web_vm_names = [
    for i in range(var.web_vm_count) :
    "${var.web_vm_name_prefix}-${format("%02d", i + 1)}"
  ]

  # cloud-init script applied to Web VMs only.
  # When install_apache = true, Apache is installed, enabled, and started.
  # The rendered YAML is base64-encoded before being passed to custom_data.
  cloud_init_web = <<-EOT
    #cloud-config
    package_update: true
    package_upgrade: false
    %{if var.install_apache}
    packages:
      - apache2
    runcmd:
      - systemctl enable --now apache2
    %{endif}
  EOT

  web_custom_data = base64encode(local.cloud_init_web)
}

# -- Availability Set ----------------------------------------------------------

resource "azurerm_availability_set" "web" {
  name                         = var.availability_set_name
  location                     = var.location
  resource_group_name          = var.resource_group_name
  platform_fault_domain_count  = 2
  platform_update_domain_count = 5
  managed                      = true
  tags                         = var.tags
}

# -- Web VM NICs ---------------------------------------------------------------

resource "azurerm_network_interface" "web" {
  count               = var.web_vm_count
  name                = "nic-${local.web_vm_names[count.index]}"
  location            = var.location
  resource_group_name = var.resource_group_name
  tags                = var.tags

  ip_configuration {
    name                          = "ipconfig-web-${count.index}"
    subnet_id                     = var.web_subnet_id
    private_ip_address_allocation = "Dynamic"
  }
}

# -- Web VMs -------------------------------------------------------------------
# Ubuntu Server 22.04 LTS Gen2 | SSH key auth only | System-assigned identity

resource "azurerm_linux_virtual_machine" "web" {
  count               = var.web_vm_count
  name                = local.web_vm_names[count.index]
  location            = var.location
  resource_group_name = var.resource_group_name
  size                = var.vm_size
  admin_username      = var.admin_username
  availability_set_id = azurerm_availability_set.web.id
  tags                = var.tags

  network_interface_ids = [
    azurerm_network_interface.web[count.index].id
  ]

  admin_ssh_key {
    username   = var.admin_username
    public_key = var.ssh_public_key_web
  }

  os_disk {
    name                 = "osdisk-${local.web_vm_names[count.index]}"
    caching              = "ReadWrite"
    storage_account_type = "Premium_LRS"
    disk_size_gb         = 64
  }

  source_image_reference {
    publisher = var.vm_image_publisher
    offer     = var.vm_image_offer
    sku       = var.vm_image_sku
    version   = var.vm_image_version
  }

  custom_data = local.web_custom_data

  disable_password_authentication = true

  identity {
    type = "SystemAssigned"
  }
}

# -- Management VM Public IP ---------------------------------------------------

resource "azurerm_public_ip" "management" {
  name                = "pip-${var.mgmt_vm_name}"
  location            = var.location
  resource_group_name = var.resource_group_name
  allocation_method   = "Static"
  sku                 = var.mgmt_public_ip_sku
  tags                = var.tags
}

# -- Management VM NIC ---------------------------------------------------------

resource "azurerm_network_interface" "management" {
  name                = "nic-${var.mgmt_vm_name}"
  location            = var.location
  resource_group_name = var.resource_group_name
  tags                = var.tags

  ip_configuration {
    name                          = "ipconfig-mgmt"
    subnet_id                     = var.management_subnet_id
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = azurerm_public_ip.management.id
  }
}

# -- Management VM -------------------------------------------------------------
# Ubuntu Server 22.04 LTS Gen2 | SSH key auth only | System-assigned identity

resource "azurerm_linux_virtual_machine" "management" {
  name                = var.mgmt_vm_name
  location            = var.location
  resource_group_name = var.resource_group_name
  size                = var.vm_size
  admin_username      = var.admin_username
  tags                = var.tags

  network_interface_ids = [
    azurerm_network_interface.management.id
  ]

  admin_ssh_key {
    username   = var.admin_username
    public_key = var.ssh_public_key_mgmt
  }

  os_disk {
    name                 = "osdisk-${var.mgmt_vm_name}"
    caching              = "ReadWrite"
    storage_account_type = "Premium_LRS"
    disk_size_gb         = 64
  }

  source_image_reference {
    publisher = var.vm_image_publisher
    offer     = var.vm_image_offer
    sku       = var.vm_image_sku
    version   = var.vm_image_version
  }

  disable_password_authentication = true

  identity {
    type = "SystemAssigned"
  }
}
