##############################################################################
# MODULE: COMPUTE - VARIABLES
##############################################################################

variable "resource_group_name" {
  type = string
}

variable "location" {
  type = string
}

variable "tags" {
  type    = map(string)
  default = {}
}

variable "web_subnet_id" {
  description = "Resource ID of the Web subnet."
  type        = string
}

variable "management_subnet_id" {
  description = "Resource ID of the Management subnet."
  type        = string
}

variable "mgmt_public_ip_sku" {
  description = "SKU for the Management VM public IP. 'Standard' is recommended for production (zone-redundant, static). Use 'Basic' only for dev/test."
  type        = string
  default     = "Standard"

  validation {
    condition     = contains(["Basic", "Standard"], var.mgmt_public_ip_sku)
    error_message = "mgmt_public_ip_sku must be either 'Basic' or 'Standard'."
  }
}

# -- VM counts and names -------------------------------------------------------

variable "web_vm_count" {
  description = "Number of Web VMs to provision (placed in an Availability Set)."
  type        = number
  default     = 2
}

variable "web_vm_name_prefix" {
  description = "Name prefix for Web VMs. Results in <prefix>-01, <prefix>-02, etc."
  type        = string
  default     = "vm-web"
}

variable "mgmt_vm_name" {
  description = "Name of the Management VM."
  type        = string
  default     = "vm-mgmt-01"
}

variable "availability_set_name" {
  description = "Name of the Availability Set used by the Web VMs."
  type        = string
  default     = "avset-web"
}

# -- VM sizing -----------------------------------------------------------------

variable "vm_size" {
  description = "Azure VM SKU size applied to all VMs in this module."
  type        = string
  default     = "Standard_B2s"
}

# -- Authentication ------------------------------------------------------------

variable "admin_username" {
  description = "Local administrator username for all VMs."
  type        = string
  default     = "azureuser"
}

variable "ssh_public_key_web" {
  description = "OpenSSH public key applied to the Web VMs. Generated by tls_private_key in the root module."
  type        = string
}

variable "ssh_public_key_mgmt" {
  description = "OpenSSH public key applied to the Management VM. Generated by tls_private_key in the root module."
  type        = string
}

# -- Bootstrap / cloud-init ----------------------------------------------------

variable "install_apache" {
  description = "When true, the cloud-init script installs, enables, and starts Apache on every Web VM at first boot. Has no effect on the Management VM."
  type        = bool
  default     = true
}

# -- OS Image ------------------------------------------------------------------
# Defaults to Ubuntu Server 22.04 LTS Gen2 (Canonical).
# Override all four values together if a different image is required.

variable "vm_image_publisher" {
  description = "Publisher of the VM marketplace image."
  type        = string
  default     = "Canonical"
}

variable "vm_image_offer" {
  description = "Offer name of the VM marketplace image."
  type        = string
  default     = "0001-com-ubuntu-server-jammy"
}

variable "vm_image_sku" {
  description = "SKU of the VM marketplace image."
  type        = string
  default     = "22_04-lts-gen2"
}

variable "vm_image_version" {
  description = "Version of the VM marketplace image. Use 'latest' to always pull the newest patch."
  type        = string
  default     = "latest"
}
