##############################################################################
# MODULE: SECURITY - VARIABLES
##############################################################################

variable "resource_group_name" {
  description = "Name of the Resource Group."
  type        = string
}

variable "location" {
  description = "Azure region."
  type        = string
}

variable "tags" {
  type    = map(string)
  default = {}
}

variable "subscription_id" {
  description = "Azure Subscription ID (used to construct scope paths for role assignments)."
  type        = string
}

variable "tenant_id" {
  description = "Azure AD Tenant ID for the Key Vault."
  type        = string
}

variable "key_vault_name" {
  description = "Globally unique Key Vault name (3-24 chars, alphanumeric and hyphens)."
  type        = string

  validation {
    condition     = can(regex("^[a-zA-Z][a-zA-Z0-9-]{1,22}[a-zA-Z0-9]$", var.key_vault_name))
    error_message = "Key Vault name must be 3-24 chars, start with a letter, contain only alphanumerics/hyphens."
  }
}

variable "storage_account_id" {
  description = "Resource ID of the Storage Account (for SP and user storage role assignments)."
  type        = string
}

# -- Service Principal ---------------------------------------------------------

variable "sp_name" {
  description = "Display name for the Azure AD Application and Service Principal."
  type        = string
  default     = "sp-infra-prod"
}

# -- SSH Private Keys ----------------------------------------------------------
# Private keys are generated by tls_private_key resources in the root module
# and passed here to be stored as Key Vault secrets.

variable "ssh_private_key_web" {
  description = "PEM-encoded SSH private key for the Web VMs."
  type        = string
  sensitive   = true
}

variable "ssh_private_key_mgmt" {
  description = "PEM-encoded SSH private key for the Management VM."
  type        = string
  sensitive   = true
}

# -- User Principals -----------------------------------------------------------

variable "user_principals" {
  description = <<-EOT
    Map of named user principals with their Azure AD object IDs and desired RBAC roles.
    Roles are automatically scoped to the correct Azure resource based on role name:
      Storage roles  -> Storage Account scope
      Key Vault roles -> Key Vault scope
      All others      -> Resource Group scope
  EOT
  type = map(object({
    object_id = string
    roles     = list(string)
  }))
  default = {}
}

# -- Add local IP -------------------------------------------------------------
variable "kv_ip_rules" {
  description = "List of public IPs/CIDRs allowed through the Key Vault firewall (e.g. Terraform runner, pipeline agent)."
  type        = list(string)
  default     = []
}